Issue : test fail on my computer for date tests on test.prompt.js
Ouput i get after make test :

AssertionError: expected 1335598954000 to be an instance of Date
    at Object.<anonymous> (/Volumes/HOMERJ/Users/despe_ki_roule/Sites/commander.js/node_modules/should/lib/should.js:355:10)
    at /Volumes/HOMERJ/Users/despe_ki_roule/Sites/commander.js/test/test.prompt.js:36:27
    at parseDate (/Volumes/HOMERJ/Users/despe_ki_roule/Sites/commander.js/lib/commander.js:737:5)
    at EventEmitter.<anonymous> (/Volumes/HOMERJ/Users/despe_ki_roule/Sites/commander.js/lib/commander.js:757:5)
    at EventEmitter.g (events.js:156:14)
    at EventEmitter.emit (events.js:67:17)
    at EventEmitter.write (/Volumes/HOMERJ/Users/despe_ki_roule/Sites/commander.js/test/test.prompt.js:12:38)
    at /Volumes/HOMERJ/Users/despe_ki_roule/Sites/commander.js/test/test.prompt.js:84:11
    at EventEmitter.expect (/Volumes/HOMERJ/Users/despe_ki_roule/Sites/commander.js/test/test.prompt.js:21:3)
    at Object.<anonymous> (/Volumes/HOMERJ/Users/despe_ki_roule/Sites/commander.js/test/test.prompt.js:82:8)